name: 'Get & Cache Dependencies'

description: 'Get the Dependencies and Cache them'

runs:
  using: composite
  steps:
    - name: install python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install poetry
      uses: abatilo/actions-poetry@v3

    - name: Setup a local virtual environment (if no poetry.toml file)
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      shell: bash
      run: |
        poetry config virtualenvs.create true --local
        poetry config virtualenvs.in-project true --local
        echo "GitHub Context:"
        echo "$GITHUB_CONTEXT"
    - uses: actions/cache@v4
      name: Define a cache for the virtual environment based on the dependencies lock file
      with:
        path: ./.venv
        key: ${{ runner.os }}-poetry-venv-${{ hashFiles('poetry.lock') }}
    - name: Install the project dependencies
      shell: bash
      run: poetry install