name: conditional-workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:


#failure() - Returns true when any previous step failed.
#success() - Returns true when all previous steps succeeded.
#always() - Returns true for all steps.
#cancelled() - Returns true when the workflow was cancelled.

jobs:
  steps-conditional:
    runs-on: macos-latest
    env:
      SUCCESS: voila
      FAILURE: huh
    steps:
      - name: success step
        id: success_step
        run: |
          if [ "$SUCCESS" == "voila" ]; then
            exit -1
          else
            exit 0
          fi
      - name: step run on failure
        if: failure() && steps.success_step.outcome == 'failure'
        run: |
          echo success step failed ${{ steps.success_step.conclusion }}
  job-conditional-failure:
    if: failure()
    needs:
      - steps-conditional
    runs-on: macos-latest
    steps:
      - name: run on steps-conditional failure
        id: success_step
        run: |
          echo "run on steps-conditional failure"
  job-conditional-success:
    if: success()
    needs:
      - steps-conditional
      - job-conditional-failure
    runs-on: macos-latest
    steps:
      - name: run on steps-conditional/job-conditional-failure success
        id: success_step
        run: |
          echo "run on steps-conditional/job-conditional-failure success"
  job-conditional-always:
    if: always()
    needs:
      - steps-conditional
      - job-conditional-failure
      - job-conditional-success
    runs-on: macos-latest
    steps:
      - name: run on steps-conditional/job-conditional-failure/job-conditional-success always
        id: success_step
        run: |
          echo "run on steps-conditional/job-conditional-failure/job-conditional-success always"
