name: container-workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  mongodb-graphql-test:
    environment: main
    runs-on: ubuntu-latest
    container:
      image: python:3.13-bookworm
    env:
      APP_ENV: ${{ secrets.APP_ENV }}
      RYUK_CONTAINER_IMAGE: ${{ secrets.RYUK_CONTAINER_IMAGE }}
      MONGODB_USER: ${{ secrets.MONGODB_USER }}
      MONGODB_CREDS: ${{ secrets.MONGODB_CREDS }}
      MONGODB_CLUSTER: ${{ secrets.MONGODB_CLUSTER }}
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Install poetry
        run: |
          apt-get update
          apt-get install pipx
          pipx ensurepath
          pipx install poetry
      - name: Setup a local virtual environment (if no poetry.toml file)
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local
      - uses: actions/cache@v4
        id: venv_cache
        name: Define a cache for the virtual environment based on the dependencies lock file
        with:
          path: ./.venv
          key: ${{ runner.os }}-poetry-venv-${{ hashFiles('poetry.lock') }}
      - name: Install the project dependencies
        if: steps.venv_cache.outputs.cache-hit != 'true'
        run: poetry install
      - name: start redpanda
        uses: redpanda-data/github-action@v0.1.4
        with:
          version: "latest"
      - name: Analysing the code with pylint
        run: |
          poetry run pylint $(git ls-files '*.py')
      - name: Run the automated tests
        run: poetry run pytest -v -s
