name: initialization-workflow
on:
  workflow_call:
    inputs:
      artifact-name:
        description: 'The name of the artifact to download'
        required: true
        default: 'workspace-folder'
        type: string
jobs:
  initialization-job:
    runs-on: ubuntu-latest

    steps:
      - name: Initialization step
        run: |
          echo "Initialization step"
          echo ${{ inputs.artifact-name }}
      - name: Initialization completion step
        run: echo "Initialization completion step"

