name: initialization-workflow
on:
  workflow_call:
    inputs:
      artifact-name:
        description: 'The name of the artifact to download'
        required: true
        default: 'workspace-folder'
        type: string
      env-name:
        description: 'The name of the environment to run'
        required: true
        type: string
    secrets:
      WF_SECRET:
        required: true
    outputs:
      result:
        description: 'The result of the initialization'
        value: ${{ jobs.initialization-job.outputs.outcome }}
jobs:
  initialization-job:
    environment: ${{ inputs.env-name }}
    runs-on: ubuntu-latest
    outputs:
      outcome: ${{ steps.set-result.outputs.result }}
    steps:
      - name: Initialization step
        run: |
          echo "Initialization step"
          echo ${{ inputs.artifact-name }}
          echo ${{ secrets.WF_SECRET }}
      - name: Initialization completion step
        run: echo "Initialization completion step"
      - name: set-result-output
        id: set-result
        run: echo "result=reuseable-wf-call-result-success" >> $GITHUB_OUTPUT

