# This is a basic workflow to help you get started with Actions

name: third-workflow
on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

env:
  WORKFLOW_NAME: ${{ github.workflow }}
  WORKFLOW_TYPE: print job workflow
jobs:
  env-vars:
    environment: main
    runs-on: macos-latest
    env:
      WORKFLOW_JOB_NAME: env-vars
      MAIN_SECRET: ${{ secrets.FIRST_SECRET }}
    steps:
      - name: print ENV VARS
        run: |
          import os
          print(os.getenv('WORKFLOW_NAME'), os.getenv('WORKFLOW_TYPE'), os.getenv('WORKFLOW_JOB_NAME'))
          print(os.getenv('MAIN_SECRET'))
        shell: python
      - name: print all env variables
        run: env
      - name: print shell
        run: |
          echo "SHELL: $SHELL"
          echo "workflow name: ${{ env.WORKFLOW_NAME }}"
          echo "workflow job name: ${{ env.WORKFLOW_JOB_NAME }}"
          echo all should have worked for us...
  env-vars2:
    runs-on: macos-latest
    env:
      DEV_SECRET: ${{ secrets.FIRST_SECRET }}
    steps:
      - name: print ENV VARS2
        run: |
          import os
          print(os.getenv('WORKFLOW_NAME'), os.getenv('WORKFLOW_TYPE'), os.getenv('WORKFLOW_JOB_NAME'))
        shell: python
      - name: print all env variables
        run: env
      - name: print shell
        run: |
          echo "SHELL: $SHELL"
          echo "workflow name: ${{ env.WORKFLOW_NAME }}"
          echo "workflow job name: ${{ env.WORKFLOW_JOB_NAME }}"
          echo only first 2 will work should have worked for us...
          echo "F_SECRET: ${{ env.DEV_SECRET }}"
          echo "secret $DEV_SECRET"
      - name: use python shell
        shell: python
        run: |
          import os
          print(os.getenv('DEV_SECRET'))
