# This is a basic workflow to help you get started with Actions

name: third-workflow


on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  WORKFLOW_NAME: ${{ github.workflow }}
  WORKFLOW_TYPE: print job workflow
jobs:
  env-vars:
    runs-on: macos-latest
    env:
      WORKFLOW_JOB_NAME: env-vars
    steps:
      - name: print ENV VARS
        run: |
          import os
          print(os.getenv('WORKFLOW_NAME'), os.getenv('WORKFLOW_TYPE'), os.getenv('WORKFLOW_JOB_NAME'))
        shell: python
      - name: print all env variables
        run: env
      - name: print shell
        run: |
          echo "SHELL: $SHELL"
          echo "shell: ${{ env.SHELL }}"
          echo both should have worked for us...
